import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Quizzy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full flex  flex-col items-center">
        <Navbar />
        <div className="fixed hidden sm:flex z-10 left-0  h-full w-16 border border-white border-l-0 border-y-0 border-opacity-15"></div>
        {children}
      </body>
    </html>
  );
}
