import type { Metadata } from "next";
import "../globals.css";
import { Navbar } from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Quizzy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full flex  flex-col items-center">
    <Navbar />
    {children}
    </div>
  );
}
